spring:
  application:
    name: aluno-fiap
  data:
    mongodb:
      uri: mongodb://localhost:27017/Fiap
  batch:
    jdbc:
      initialize-schema: always
  mvc:
    pathmatch:
      matching-strategy: 'ant_path_matcher'
  inputfile: 'content/lista_alunos.txt'

server:
  port : 8081


